In [1]:
import pandas as pd

In [3]:
dataset=pd.read_csv("insurance_pre.csv")

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [7]:
dependent=dataset[['charges']]
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
scy=StandardScaler()
y_train=scy.fit_transform(y_train)
y_test=scy.transform(y_test)

In [13]:
from sklearn.svm import SVR
regressor=SVR(kernel='rbf',C=1000)
regressor.fit(x_train,y_train)

C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=1000)

In [14]:
regressor.intercept_

array([0.34961713])

In [15]:
regressor.n_support_

array([410], dtype=int32)

In [17]:
regressor.support_

array([  2,   4,   6,   8,   9,  12,  13,  15,  21,  22,  25,  26,  29,
        30,  33,  36,  37,  39,  41,  44,  45,  46,  47,  52,  54,  58,
        59,  61,  66,  68,  69,  70,  71,  72,  75,  76,  85,  87,  90,
        91,  92,  95, 100, 104, 105, 107, 113, 117, 118, 121, 123, 125,
       126, 129, 132, 138, 147, 149, 153, 155, 158, 162, 164, 165, 168,
       169, 174, 177, 178, 179, 183, 187, 192, 193, 195, 197, 199, 200,
       201, 202, 203, 204, 206, 207, 209, 211, 212, 213, 214, 215, 218,
       220, 227, 231, 233, 236, 237, 238, 239, 240, 241, 242, 243, 245,
       247, 251, 253, 255, 257, 259, 263, 264, 266, 267, 273, 274, 276,
       279, 281, 285, 286, 295, 296, 297, 300, 308, 312, 315, 317, 319,
       321, 322, 323, 326, 331, 334, 335, 337, 338, 343, 344, 347, 348,
       349, 351, 353, 357, 360, 361, 364, 365, 366, 370, 373, 375, 376,
       382, 384, 386, 387, 388, 389, 391, 392, 395, 397, 399, 400, 401,
       410, 412, 413, 418, 421, 422, 423, 424, 426, 427, 428, 430, 433,
       436, 437, 442, 444, 445, 446, 447, 448, 449, 450, 452, 453, 454,
       458, 459, 460, 464, 468, 470, 472, 474, 478, 481, 484, 486, 487,
       490, 491, 492, 493, 494, 495, 497, 499, 505, 507, 510, 512, 513,
       514, 519, 522, 523, 527, 528, 530, 532, 535, 536, 537, 540, 543,
       544, 545, 547, 548, 549, 550, 554, 558, 560, 562, 563, 564, 566,
       568, 570, 573, 575, 576, 579, 583, 584, 585, 587, 590, 593, 596,
       598, 601, 603, 604, 605, 606, 607, 608, 611, 612, 615, 622, 623,
       624, 625, 628, 634, 639, 641, 645, 648, 649, 653, 655, 656, 657,
       658, 659, 660, 661, 662, 674, 676, 678, 682, 685, 688, 689, 692,
       695, 696, 698, 700, 701, 702, 708, 710, 713, 717, 723, 724, 725,
       727, 728, 729, 730, 731, 734, 735, 737, 738, 741, 744, 745, 748,
       749, 750, 751, 753, 758, 761, 762, 768, 777, 779, 780, 781, 783,
       784, 785, 786, 790, 794, 795, 798, 799, 800, 801, 805, 806, 807,
       808, 809, 811, 813, 815, 817, 825, 826, 827, 828, 830, 831, 833,
       834, 837, 838, 839, 842, 844, 846, 847, 850, 852, 855, 856, 859,
       862, 865, 866, 868, 870, 873, 875, 876, 877, 880, 881, 884, 888,
       895, 896, 897, 898, 900, 904, 906, 907, 908, 909, 910, 911, 915,
       918, 927, 928, 929, 930, 933, 935], dtype=int32)

In [19]:
y_pred=regressor.predict(x_test)

In [21]:
from sklearn.metrics import r2_score
r2_score=r2_score(y_test,y_pred)
r2_score

0.8158353481270235

In [23]:
import pickle

In [24]:
filename="insurance_svr_model.sav"

In [25]:
pickle.dump(regressor,open("insurance_svr_model.sav",'wb'))

In [26]:
preinput=sc.transform([[19,0,34.5,0,0]])
preinput

C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([[-1.46169465, -4.93438791, 27.76683317, -0.97676557, -0.50466988]])

In [27]:
loaded_model=pickle.load(open("insurance_svr_model.sav",'rb'))
result=loaded_model.predict(preinput)

In [28]:
result

array([0.34961713])

In [34]:
preoutput=scy.inverse_transform([result])
print("The Expected insurenace charge is",preoutput[0][0])

The Expected insurenace charge is 17384.18722655826